# Generated by Django 3.2.11 on 2022-09-06 20:48

from django.db import migrations, models
import django.db.models.deletion
import tours.models
import tours.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_prev_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tours.models.get_upload_path, validators=[tours.validators.validate_file_size, tours.validators.validate_file_type])),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_photos', to='tours.review')),
            ],
        ),
    ]
